name: ClimaticEvents
main: awt.breeze.climaticEvents.ClimaticEvents
version: ${project.version}
description: Plugin extreme climatic events
api-version: 1.17
softdepend:
  - WorldGuard
  - WorldEdit
  - PlaceholderAPI
commands:
  climaticevents:
    description: Commands for ClimaticEvents plugin.
    usage: /<command> <subcommand>
    permission: climaticevents.admin
    aliases: [ce]
    children:
      reload:
        description: Reload the plugin configuration.
        permission: climaticevents.reload
      resetdays:
        description: Reload the days interval.
        permission: climaticevents.resetdays
      startevent:
        description: Start a random event.
        permission: climaticevents.startevent
      forcesolarflare:
        description: Start the solar flare event.
        permission: climaticevents.startevent
      forceacidrain:
        description: Start the acid rain event.
        permission: climaticevents.startevent
      forceelectricstorm:
        description: Start the electric storm event.
        permission: climaticevents.startevent
      cancelevent:
        description: Cancel the current event.
        permission: climaticevents.cancelevent
      nextevent:
        description: Show the days remaining for the next event.
        permission: climaticevents.nextevent
        default: true
      spawnsolarboss:
        description: Spawn the solar boss.
        permission: climaticevents.spawnboss
      spawnrainboss:
        description: Spawn the rain boss.
        permission: climaticevents.spawnboss
      spawnstormboss:
        description: Spawn the storm boss.
        permission: climaticevents.spawnboss
      killsolarboss:
        description: Kill the solar boss.
        permission: climaticevents.killboss
      killrainboss:
        description: Kill the rain boss.
        permission: climaticevents.killboss
      killstormboss:
        description: Kill the storm boss.
        permission: climaticevents.killboss
      chest:
        description: Spawn chest drop.
        permission: climaticevents.chest
      killchest:
        description: Remove chest drop.
        permission: climaticevents.killchest
      on:
        description: Enable plugin.
        permission: climaticevents.toggle
      off:
        description: Disable plugin.
        permission: climaticevents.toggle
      panel:
        description: Open manager panel.
        permission: climaticevents.panel
      mode:
        description: change mode.
        permission: climaticevents.mode
      newtime:
        description: change interval days.
        permission: climaticevents.newtime

permissions:
  climaticevents.admin:
    description: Permission to use all commands.
    default: op
    children:
      climaticevents.reload: true
      climaticevents.resetdays: true
      climaticevents.startevent: true
      climaticevents.cancelevent: true
      climaticevents.nextevent: true
      climaticevents.spawnboss: true
      climaticevents.killboss: true
      climaticevents.chest: true
      climaticevents.killchest: true
      climaticevents.toggle: true
      climaticevents.panel: true
      climaticevents.mode: true